# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

     category_repository:
          class: AppBundle\Entity\Repository\CategoryRepository
          factory_service: doctrine.orm.default_entity_manager
          factory_method: getRepository
          arguments: [AppBundle\Entity\Category]

     article_repository:
               class: AppBundle\Entity\Repository\ArticleRepository
               factory_service: doctrine.orm.default_entity_manager
               factory_method: getRepository
               arguments: [AppBundle\Entity\Article]

     user_repository:
                    class: AppBundle\Entity\Repository\UserRepository
                    factory_service: doctrine.orm.default_entity_manager
                    factory_method: getRepository
                    arguments: [AppBundle\Entity\User]

     department_repository:
                    class: AppBundle\Entity\Repository\DepartmentRepository
                    factory_service: doctrine.orm.default_entity_manager
                    factory_method: getRepository
                    arguments: [AppBundle\Entity\Department]

     category_manager:
               class: AppBundle\Entity\Manager\CategoryManager
               arguments: ['@category_repository']

     article_manager:
                class: AppBundle\Entity\Manager\ArticleManager
                arguments: ['@article_repository', '@category_manager']

     department_manager:
                     class: AppBundle\Entity\Manager\DepartmentManager
                     arguments: ['@department_repository']
