<?php
use  Symfony\Component\HttpFoundation\Response as Response;
use  \Doctrine\ORM\EntityManager as EntityManager;

 class ArticleManager extends EntityManager{

     public static function create($conn, \Doctrine\ORM\Configuration $config, \Doctrine\Common\EventManager $eventManager = null)
     {
         return parent::create($conn, $config, $eventManager); // TODO: Change the autogenerated stub
     }

     public function save(Response $response){

     }
 }